### ISSUE TITLE
cors problem

### ISSUE THREAD

**Issue by windgaucho** [Blacktoviche/springboot-graphql-sqqr-jwt-demo#2]
Hello, thanks for this excellent example.

I am using your code in my application and I am able to login using postman and insomia, but when I try to login from my client application (vue.js app) I am getting the following error:

````
Access to fetch at 'http://localhost:9010/graphql' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
````
Can you please show me how to configure cors in the server? 

Thanks.

Luis

**Comment by Blacktoviche** [comment]
Hello Luis
In WebSecurityConfig class try adding this ` .cors().and()` to line 50

**Comment by windgaucho** [comment]
Thank you @Blacktoviche it works now !!

**Comment by Blacktoviche** [comment]
Great, you are welcome
