### ISSUE TITLE
Signin Request is not filtered

### ISSUE THREAD

**Issue by sarbhsinghal** [Blacktoviche/springboot-graphql-sqqr-jwt-demo#3]
My SecurityConfig file is as follows

 @Override
    protected void configure(HttpSecurity httpSecurity) throws Exception {
        httpSecurity
                .csrf().disable()
                .authorizeRequests()
                .antMatchers("/graphql").permitAll()
                .antMatchers("/graphiql").permitAll()
                .anyRequest().authenticated();
              
        JwtFilter authenticationFilter = new JwtFilter(userDetailsService(), jwtTokenUtil);
      httpSecurity.addFilterBefore(authenticationFilter, UsernamePasswordAuthenticationFilter.class);
    }

When i execute signin mutation, It also went to filter. Since it does not get any token so its gets blocked. Why is it so?

**Comment by Blacktoviche** [comment]
It shouldn't . here is the repository security config code

`  @Override
    protected void configure(HttpSecurity httpSecurity) throws Exception {
        httpSecurity
                .csrf().disable()
                .exceptionHandling().and()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
                .authorizeRequests()
                .antMatchers("/graphql/**").permitAll()
                .anyRequest().authenticated();
        JwtFilter authenticationFilter = new JwtFilter(userDetailsService(), jwtTokenUtil);
        httpSecurity
                .addFilterBefore(authenticationFilter, UsernamePasswordAuthenticationFilter.class);
    }`

Try it like that and tell me what happen. It work perfect
